ROSController:
  image: yuriyfedyuk/ros_controller:latest
  volumes:
    - .:/ros_controller
  command: sh -c 'ros2 launch litmus_ros_bridge nats_bridge.launch.py input_topics:="['ros_input_topic']"'
  restart: "always"