version: "2"
services: 
    ros2_container:
        container_name: ros_controller
        build: ros_controller/docker 
        environment:
            - ENV=Development
            - REPO_USER=${REPO_USER}
            - REPO_PASS=${REPO_PASS}
        volumes:
            - .:/ros_controller